name: Playwright Test Report Deployment
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies for WebKit
        run: |
              sudo apt-get update
              sudo apt-get install -y \
                libwoff1 \
                libvpx7 \
                libevent-2.1-7 \
                libopus0 \
                libgstreamer1.0-0 \
                libgstreamer-plugins-base1.0-0 \
                libgstreamer-gl1.0-0 \
                libgstreamer-plugins-good1.0-0 \
                libgstreamer-plugins-bad1.0-0 \
                libflite1 \
                libharfbuzz-icu0 \
                libhyphen0 \
                libgles2-mesa \
                libavif13 \
                libx264-dev \
      - name: Install dependencies
        run: npm install
      - name: Run Playwright tests
        run: npx playwright test --reporter=html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./test-results/html-report